[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
owning_ref = "0.4.1"
wasm-bindgen = "0.2.83"

[dependencies.web-sys]
web-sys = "0.3.60"
features = [
	"console"
]
