name: Build and Deploy client

on:
    workflow_dispatch: {}
    push:
        branches:
            - "master"

jobs:
    build-deploy:
        name: Build and Deploy Client
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: latest
            - uses: jetli/wasm-pack-action@v0.4.0
              with:
                  version: latest
            - name: wasm-pack build
              working-directory: ./client/wasm
              run: |
                  npm run build
            - name: vite build
              working-directory: ./client
              run: |
                  npm ci
                  npm run build
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: ./client/dist
